### ISSUE TITLE
Why is the rainfall as a bubble?

### ISSUE THREAD

**Issue by WSDguy2014** [azekillDIABLO/Bountiful-Blossoms--Halcyon-Days#1]
![screenshot_20170409_102807](https://cloud.githubusercontent.com/assets/13905392/24835621/55426444-1d0f-11e7-84b1-6e4e6d10bf90.png)
That does not make sense, is that old rain texture from old weather mod?

**Comment by RodrigueLemaire** [comment]
has been fixed in new release, it was a nonsense. It is the old rain mod texture (snowdrift mod)
